#!/bin/bash

# CITRIX Reciever install on ubuntu 14.04

# STEP 1
# download newest reciever from website

# STEP 2 
# install it

# STEP 3
# make sure Firefox plugin is set to "always active"

# STEP 4
# link in mozilla's CA certs to citrix
sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/

# STEP 5
# update CA cert. list
sudo c_rehash /opt/Citrix/ICAClient/keystore/cacerts/

# STEP 6 
# get chrome to work
xdg-mime default wfica.desktop application/x-ica

# OPTIONAL STEPS:
# https://help.ubuntu.com/community/CitrixICAClientHowTo
