#!/bin/bash

# http://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
git config --global user.name "John Doe"
git config --global user.email "johndoe@example.com"

# https://help.github.com/articles/generating-ssh-keys/
# Creates a new ssh key using the provided email
ssh-keygen -t rsa -C "johndoe@example.com"
    # Enter file ... : just press enter
    # Make a strong passphrase
eval "$(ssh-agent -s)"
    # start the ssh-agent
ssh-add ~/.ssh/id_rsa
#
# add ssh key to github (steps in above link)
#
# see if it worked
ssh -T git@github.com

# connection refused? Try this:
ssh -T -p 443 git@ssh.github.com
    # use https port
# worked? Follow these steps.
# https://help.github.com/articles/using-ssh-over-the-https-port/
