#!/bin/bash
#
# FOR: 14.04 SERVER on a HP z420 Workstation for ORNL
#
# script to install all the extra stuff I like in ubuntu. When java installs you 
# will need to accept the UELA. May need to aprove changes from time to time 
# (-y should take care of that). Make sure to read through this list and comment 
# out lines you do not want with a '#'. If it ever says that it can't find a 
# package, that whole line will not go, so deleate that package from line, and 
# then re-run the script (will not hurt to run more than once).
#
#
# When booting, you may see:
#    error:  Diskfilter writes are not supported
# This is an error in grub when using RAID, fix is here:
#    http://askubuntu.com/questions/468466/why-this-occurs-error-diskfilter-writes-are-not-supported
#
# proxy connections with ssh
sudo apt-get install -y corkscrew
#
# Ubuntu stuff
sudo apt-get install -y ubuntu-desktop
sudo apt-get install -y ppa-purge unity-tweak-tool
# stop invading my privacy yo. 
#wget -q -O - https://fixubuntu.com/fixubuntu.sh | bash
## to be able to see windows partitions
#sudo apt-get install -y ntfs-config # to see windows drive
#
# Media stuff
sudo apt-get install -y ttf-liberation flashplugin-installer
sudo apt-get install -y ubuntu-restricted-addons ubuntu-restricted-extras
sudo apt-get install -y skype
sudo apt-get install -y synergy
#
# prorgraming stuff
sudo apt-get install -y build-essential cvs vim-gnome cmake cmake-curses-gui
sudo sed -i 's/gedit.desktop/gvim.desktop/g' /etc/gnome/defaults.list 
    # make gvim defualt text editor -- edit to suit your preferences. 
sudo apt-get install -y gedit-plugins doxygen geany geany-plugins
sudo apt-get install -y python-dev python-numpy python-matplotlib python-scientific python-pip
sudo apt-get install -y python-scipy python-sphinx python-pyproj python-netcdf
sudo apt-get install -y bzr bzr-doc
    # Version control system (my pref)
sudo apt-get install -y git git-doc 
    # Version control system (most popular)
sudo apt-get install -y colordiff
#
# Fortran
sudo apt-get install -y gfortran
# C++ Libraries
sudo apt-get install -y libboost-all-dev libboost-doc
    # boost libraries: http://www.boost.org/ 
sudo apt-get install -y libcgal-dev
    # CGAL libraries: http://doc.cgal.org/
# Science stuff
sudo apt-get install -y gnuplot units graphvis
    # units is a comand line unit converter
sudo apt-get install -y ferret-vis ncl-ncarg
sudo ln -s /usr/share/ncarg /usr/lib/ncarg
    # this fixes a bug in NCL, fixed in NCL 6.2.0.1ubuntu1
    # test first with:
    #ng4ex gsun01n -clean
sudo apt-get install -y octave
sudo apt-get install -y texlive-full bibtex2html latexdiff diffpdf perl-doc
sudo apt-get install -y autotrace engauge-digitizer # for digitizing plots
# GMT Generic Mapping tools -- build from source
sudo apt-get install -y libgdal1-dev libfftw3-dev libpcre3-dev GraphicsMagick subversion
    # download source using:
    # svn checkout svn://gmtserver.soest.hawaii.edu/gmt5/trunk gmt5-dev
    # then follow build instructions
# HDF5
sudo apt-get install -y libhdf5-dev hdf5-tools hdf5-helpers flex
# NetCDF
sudo apt-get install -y libnetcdf-dev netcdf-bin netcdf-doc nco ncview
# netCDF python support (need netcdf and HDF5 first)
#sudo apt-get install -y libfreetype6-dev libxft-dev
    # fixes known bug with pip and freetypes -- not sure if needed
sudo -E pip install netcdf4
# LBLAS
sudo apt-get install -y libblas-dev
# MPI
sudo apt-get install -y openmpi-bin libopenmpi-dev
# LAPACK
sudo apt-get install -y liblapack-dev

## FEM Framework -- http://fenicsproject.org/download/ubuntu_details.html
#sudo add-apt-repository ppa:fenics-packages/fenics
#sudo apt-get update
#sudo apt-get install -y fenics
#sudo apt-get dist-upgrade
#sudo apt-get install -y libcgal9 
    #this was needed for first demo script, wtf? Are there more dep. not installed?

## PISM Dependencies
sudo apt-get install -y libgsl0-dev libudunits2-dev cdo libproj-dev libx11-dev
    # Will need PETSc -- build from source!
    # Build PISM from source as well!

## CISM Dependencies
## Will need Trilinos
    # install from http://trilinos.org/
    # this will take a lot of time to build. Seriously. 
    # use CISM documentation to install.
#
# File stuff
sudo apt-get install -y p7zip-full
    # file extraction
sudo apt-get install -y unison-gtk 
    # file sync program
sudo apt-get install -y filezilla 
    # cross platform FTP client 
sudo apt-get install -y nautilus-open-terminal 
    # adds "open in terminal" option in right click menu
sudo apt-get install -y gparted 
    # disk utility
#
# Image stuff:  gimp -> photoshop, 
#               inkscape -> illustrator, 
#               xournal -> annotates pdfs, 
#               icoutils -> .ico creator
sudo apt-get install -y gimp inkscape xournal icoutils
#
# Video Editor:
sudo apt-get install -y openshot
# java
sudo apt-get install -y openjdk-7-jre
#
# debian configuration tools
sudo apt-get install -y dconf-tools gconf-editor
    # This is how you change the gedit-terminal colors! 
#
# Weather and system monitor indicators:
sudo add-apt-repository ppa:atareao/atareao
sudo apt-get update
sudo apt-get install -y my-weather-indicator
#
sudo apt-get install -y indicator-multiload
#
#
# Fitbit sync
# sudo apt-get isntall -y python-usb python-requests
#
# Clean up
sudo apt-get autoremove
#
# set up windows partition support
# sudo ntfs-config 
#
#
# Software to build (see notes above):
# PETSc                     X
# PISM                      X
# Trilinos                  X
# CISM                      X
#
# Other things to Install:
#    Mendeley               X
#    GoogleChrome           X
#    GoogleEarth            -
    # 64bit version doesn't work as ia32-libs is depreciated and no longer available (google does not provide
    # an actual 64bit version). Need to install 32bit version from website and install these first:
    #sudo apt-get install -y libc6-i386 libglib2.0-0:i386 libsm6:i386 libglu1-mesa:i386 libgl1-mesa-glx:i386 
    #sudo apt-get install -y libxext6:i386 libxrender1:i386 libx11-6:i386 libfontconfig1:i386 lsb-core
    #sudo apt-get install -y lib32nss-mdns
    # see more info here: https://help.ubuntu.com/community/GoogleEarth
#
# To configure after install:
# Empathy                   -
# Thunderbird               X <-- see OLUG guide
# home.git                  X <-- on jhkennedy.org -- see notes below
# Mendeley                  X
# launch weather indicator  X
# launch sysmonitor indic.  X
# Synergy                   X
# enable workspaces         X <-- in appearance and then use unity-tweak-tool to set number or wanted workspaces

#### NOTES ####

# home.git setup
# Normal git clone commands for the home.git repository will fail because you will be cloning into a non-empty
# directory. In order to clone the repository you will need to:
  # cd ~
  # git init
  # git remote add origin joseph@jhkennedy.org:home.git
  # git fetch
  # git checkout -t origin/ORNL
  # git reset --hard HEAD
# WARNING: this will wipe any current information in the tracked files. BE SURE THIS IS WHAT YOU WANT TO DO. 
